AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  poja-sam-version-router

Globals:
  Function:
    Timeout: 900

    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  Env:
    Type: String

Resources:
  PojaSamVersionRouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poja_sam_router/

      Handler: app.lambda_handler

      Runtime: python3.11

      MemorySize: 1024

      Architectures:
      - arm64
      
      Events:
        Gen:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

      Role: !Sub '{{resolve:ssm:/poja-api/${Env}/execution/role-arn}}'

      Environment:
        Variables:
          POJA_SAM_API_KEY: !Sub '{{resolve:ssm:/poja-api/${Env}/poja/sam/api/key}}'

      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  PojaSamVersionRouterFunctionUrl:
    Description: Poja Sam Version Router Lambda Function URL
    Value:
      Fn::GetAtt: PojaSamVersionRouterFunctionUrl.FunctionUrl
  PojaSamVersionRouterFunction:
    Description: Poja Sam Version Router Lambda Function ARN
    Value: !GetAtt PojaSamVersionRouterFunction.Arn
